# Generated by Django 5.0.7 on 2025-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_leader_delete_leadership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='caption',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='all_uploaded/gallery_images/'),
        ),
    ]
