# Generated by Django 5.0.7 on 2025-06-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_rename_caption_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
    ]
